const fakeData = [
  {
    id: 0,
    name: "Hanif",
    from: "Dhaka",
    to: "Khulna",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Khulna",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 1,
    name: "Hanif",
    from: "Dhaka",
    to: "Khulna",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Khulna",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 500,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 2,
    name: "Shamoly",
    from: "Dhaka",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Sayedabad",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-12",
    returnDate: "10/6/2020",
  },
  {
    id: 3,
    name: "Green Line",
    from: "Dhaka",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-19",
    returnDate: "2020-11-20",
  },
  {
    id: 4,
    name: "Ena",
    from: "Dhaka",
    to: "Sylhet",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-10-15",
    returnDate: "2020-12-20",
  },
  {
    id: 5,
    name: "Hanif",
    from: "Khulna",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Khulna",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-16",
    returnDate: "10/6/2020",
  },
  {
    id: 6,
    name: "Shamoly",
    from: "Khulna",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Khulna",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-17",
    returnDate: "10/6/2020",
  },
  {
    id: 7,
    name: "Green Line",
    from: "Khulna",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Khulna",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-25",
    returnDate: "10/6/2020",
  },
  {
    id: 8,
    name: "Star Line",
    from: "Khulna",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Khulna",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-21",
    returnDate: "10/6/2020",
  },
  {
    id: 9,
    name: "Star Line",
    from: "Sylhet",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-22",
    returnDate: "10/6/2020",
  },
  {
    id: 10,
    name: "Green Line",
    from: "Sylhet",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-23",
    returnDate: "10/6/2020",
  },
  {
    id: 11,
    name: "Green Line",
    from: "Sylhet",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-24",
    returnDate: "10/6/2020",
  },
  {
    id: 12,
    name: "Green Line",
    from: "Sylhet",
    to: "Mymensingh",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-27",
    returnDate: "10/6/2020",
  },
  {
    id: 13,
    name: "Green Line",
    from: "Rajshahi",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-28",
    returnDate: "10/6/2020",
  },
  {
    id: 14,
    name: "Hanif",
    from: "Rajshahi",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-29",
    returnDate: "10/6/2020",
  },
  {
    id: 15,
    name: "Hanif",
    from: "Rajshahi",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Rajshahi",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-01",
    returnDate: "10/6/2020",
  },
  {
    id: 16,
    name: "Ena",
    from: "Rajshahi",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-05",
    returnDate: "10/6/2020",
  },
  {
    id: 17,
    name: "Ena",
    from: "Chittagong",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Chittagong",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-06",
    returnDate: "10/6/2020",
  },
  {
    id: 18,
    name: "Ena",
    from: "Chittagong",
    to: "Rajshahi",
    bustType: true,
    startingPoint: "Chittagong",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-08",
    returnDate: "10/12/2020",
  },
  {
    id: 19,
    name: "Green Line",
    from: "Chittagong",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Chittagong",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-11",
    returnDate: "10/12/2020",
  },
  {
    id: 20,
    name: "Hanif",
    from: "Chittagong",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 21,
    name: "Hanif",
    from: "Barishal",
    to: "Khulna",
    bustType: false,
    startingPoint: "Barishal",
    endingPoint: "Khulna",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 22,
    name: "Shaymoly",
    from: "Barisal",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Barisal",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 500,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 23,
    name: "Shamoly",
    from: "Mymensingh",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Mymensingh",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-12",
    returnDate: "10/6/2020",
  },
  {
    id: 24,
    name: "Green Line",
    from: "Mymensingh",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Mymensingh",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-19",
    returnDate: "2020-11-20",
  },
  {
    id: 25,
    name: "Ena",
    from: "Dhaka",
    to: "Rangpur",
    bustType: false,
    startingPoint: "Dhaka",
    endingPoint: "Rangpur",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-10-15",
    returnDate: "2020-12-20",
  },
  {
    id: 26,
    name: "Hanif",
    from: "Rangpur",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Rangpur",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-16",
    returnDate: "10/6/2020",
  },
  {
    id: 27,
    name: "Shamoly",
    from: "Bagherhat",
    to: "Khulna",
    bustType: true,
    startingPoint: "Bagherhat",
    endingPoint: "Khulna",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-17",
    returnDate: "10/6/2020",
  },
  {
    id: 28,
    name: "Green Line",
    from: "Jamalpur",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Jamalpur",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-25",
    returnDate: "10/6/2020",
  },
  {
    id: 29,
    name: "Star Line",
    from: "Khulna",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Khulna",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-21",
    returnDate: "10/6/2020",
  },
  {
    id: 30,
    name: "Star Line",
    from: "Sylhet",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-22",
    returnDate: "10/6/2020",
  },
  {
    id: 31,
    name: "Green Line",
    from: "Sylhet",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-23",
    returnDate: "10/6/2020",
  },
  {
    id: 32,
    name: "Green Line",
    from: "Sylhet",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-24",
    returnDate: "10/6/2020",
  },
  {
    id: 33,
    name: "Green Line",
    from: "Sylhet",
    to: "Mymensingh",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-27",
    returnDate: "10/6/2020",
  },
  {
    id: 34,
    name: "Green Line",
    from: "Bogra",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Bogra",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-28",
    returnDate: "10/6/2020",
  },
  {
    id: 35,
    name: "Hanif",
    from: "Dhaka",
    to: "Bogra",
    bustType: true,
    startingPoint: "Dhaka",
    endingPoint: "Bogra",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-29",
    returnDate: "10/6/2020",
  },
  {
    id: 36,
    name: "Hanif",
    from: "Rajshahi",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Rajshahi",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-01",
    returnDate: "10/6/2020",
  },
  {
    id: 37,
    name: "Ena",
    from: "Rajshahi",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-05",
    returnDate: "10/6/2020",
  },
  {
    id: 38,
    name: "Ena",
    from: "Chittagong",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Chittagong",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-06",
    returnDate: "10/6/2020",
  },
  {
    id: 39,
    name: "Ena",
    from: "Chittagong",
    to: "Rajshahi",
    bustType: true,
    startingPoint: "Chittagong",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-08",
    returnDate: "10/12/2020",
  },
  {
    id: 40,
    name: "Green Line",
    from: "Dhaka",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Dhaka",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-11",
    returnDate: "10/12/2020",
  },
  {
    id: 41,
    name: "Hanif",
    from: "Chittagong",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 42,
    name: "Green Line",
    from: "Bandarban",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Bandarban",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-11",
    returnDate: "10/12/2020",
  },
  {
    id: 43,
    name: "Hanif",
    from: "Bandarban",
    to: "Dhaka",
    bustType: true,
    startingPoint: "Bandarban",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
];

export default fakeData;
