const fakeData = [
  {
    id: 1,
    from: "Dhaka",
    to: "Khulna",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Khulna",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-20",
    returnDate: "10/6/2020",
  },
  {
    id: 2,
    from: "Dhaka",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Sayedabad",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-12",
    returnDate: "10/6/2020",
  },
  {
    id: 3,
    from: "Dhaka",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-11-10",
    returnDate: "2020-11-20",
  },
  {
    id: 4,
    from: "Dhaka",
    to: "Sylhet",
    bustType: false,
    startingPoint: "Sayedabad",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "2020-10-15",
    returnDate: "2020-12-20",
  },
  {
    id: 5,
    from: "Khulna",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Khulna",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 6,
    from: "Khulna",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Khulna",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 7,
    from: "Khulna",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Khulna",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 8,
    from: "Khulna",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Khulna",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 9,
    from: "Sylhet",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 10,
    from: "Sylhet",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 11,
    from: "Sylhet",
    to: "Rajshahi",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 12,
    from: "Sylhet",
    to: "Mymensingh",
    bustType: true,
    startingPoint: "Sylhet",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 13,
    from: "Rajshahi",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Sylhet",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 14,
    from: "Rajshahi",
    to: "Chittagong",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Chittagong",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 15,
    from: "Rajshahi",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Rajshahi",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 16,
    from: "Rajshahi",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 17,
    from: "Chittagong",
    to: "Dhaka",
    bustType: false,
    startingPoint: "Chittagong",
    endingPoint: "Dhaka",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
  {
    id: 18,
    from: "Chittagong",
    to: "Rajshahi",
    bustType: true,
    startingPoint: "Chittagong",
    endingPoint: "Rajshahi",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "19/11/2020",
    returnDate: "10/12/2020",
  },
  {
    id: 19,
    from: "Chittagong",
    to: "Mymensingh",
    bustType: false,
    startingPoint: "Chittagong",
    endingPoint: "Mymensingh",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/11/2020",
    returnDate: "10/12/2020",
  },
  {
    id: 20,
    from: "Chittagong",
    to: "Sylhet",
    bustType: true,
    startingPoint: "Rajshahi",
    endingPoint: "Sylhet",
    departureTime: "6:20 PM",
    arrivalTime: "9:26 AM",
    seatsAvailable: 26,
    fare: 452,
    journeyDate: "10/8/2020",
    returnDate: "10/6/2020",
  },
];

export default fakeData;
